name: actions-build-image

on:
  workflow_call:
    inputs:
      docker_registry:
        description: 'docker registry'
        required: true
        type: string
      docker_tag:
        description: 'docker tag'
        required: false
        type: string
        default: 'latest'

jobs:
  build-image:
    runs-on: self-hosted
    steps:
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.docker_registry }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ inputs.docker_registry }}:${{ github.run_id }},${{ inputs.docker_registry }}:${{ inputs.docker_tag }}
          build-args: |
            version=${{ github.run_id }}