name: actions-go-build

on:
  workflow_call:

jobs:
  build-go-app:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Go Modules
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Test
        run: |
          go mod tidy
          go test ./... -coverprofile coverage.out
          go tool cover -html=coverage.out -o out-${{ github.run_id }}.html

      - name: Build App
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o app
