name: actions-wechat-notify

on:
  workflow_call:
    inputs:
      bot_key:
        description: 'WeChat Work bot webhook key'
        required: true
        type: string
      custom_message:
        description: 'Custom message to append'
        required: false
        type: string
        default: ''
      environment:
        description: 'Deployment environment'
        required: false
        type: string
        default: 'production'

jobs:
  notify:
    runs-on: self-hosted
    steps:
      - name: notify(success)
        uses: stvenx/wechat-work-messenger@v2
        if: success()
        env:
          BOT_KEY: ${{ inputs.bot_key }}
          MSG_TYPE: markdown
          POST_MESSAGE: |
            ## ✅ 部署成功
            
            **仓库:** <font color="info">${{ github.repository }}</font>
            **分支:** <font color="info">${{ github.ref_name }}</font>
            **环境:** <font color="info">${{ inputs.environment }}</font>
            **提交作者:** <font color="info">${{ github.event.head_commit.author.name }}</font>
            **提交时间:** ${{ github.event.head_commit.timestamp }}
            **构建日志:** [查看详情](${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }})
            
            **提交信息:**
            ```
            ${{ github.event.head_commit.message }}
            ```
            
            ${{ inputs.custom_message && format('**备注:** {0}', inputs.custom_message) || '' }}

      - name: notify(failure)
        uses: stvenx/wechat-work-messenger@v2
        if: failure()
        env:
          BOT_KEY: ${{ inputs.bot_key }}
          MSG_TYPE: markdown
          POST_MESSAGE: |
            ## ❌ 部署失败
            
            **仓库:** <font color="warning">${{ github.repository }}</font>
            **分支:** <font color="warning">${{ github.ref_name }}</font>
            **环境:** <font color="warning">${{ inputs.environment }}</font>
            **提交作者:** <font color="warning">${{ github.event.head_commit.author.name }}</font>
            **提交时间:** ${{ github.event.head_commit.timestamp }}
            **错误日志:** [查看详情](${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }})
            
            **提交信息:**
            ```
            ${{ github.event.head_commit.message }}
            ```
            
            **提交ID:** `${{ github.sha }}`
            
            ${{ inputs.custom_message && format('**备注:** {0}', inputs.custom_message) || '' }}