name: actions-wx-notify

on:
  workflow_call:
    inputs:
      bot_key:
        description: 'wechat bot key'
        required: true
        default: 'c10e1711-aec4-476f-9d8a-badfb4b2d3df'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: notify(success)
        uses: stvenx/wechat-work-messenger@v2
        if: success()
        env:
          BOT_KEY: {{ inputs.bot_key }}
          MSG_TYPE: markdown
          POST_MESSAGE: |
            <font color=\"info\">${{ github.GITHUB_REPOSITORY }}:${{ github.ref_name }} 部署成功 </font> \n
            提交作者： <font color=\"info\"> ${{ github.event.head_commit.author.name }} </font> \n
            构建日志： <font color=\"info\"> [${{ github.event.repository.html_url }}/actions/runs/${{github.run_id}}](${{ github.event.repository.html_url }}/actions/runs/${{github.run_id}}) </font> \n
            提交记录：
            ${{ github.COMMIT_MSG }}\n

      - name: notify(failure
        uses: stvenx/wechat-work-messenger@v2
        if: failure()
        env:
          BOT_KEY: {{ inputs.bot_key }}
          MSG_TYPE: markdown
          POST_MESSAGE: |
            ❗️❗️❗️ <font color=\"warning\">${{ github.GITHUB_REPOSITORY }}:${{ github.ref_name }} 部署失败 </font> \n
            提交作者： <font color=\"warning\"> ${{ github.event.head_commit.author.name }} </font> \n
            构建日志： <font color=\"warning\"> [${{ github.event.repository.html_url }}/actions/runs/${{github.run_id}}](${{ github.event.repository.html_url }}/actions/runs/${{github.run_id}}) </font> \n
            提交记录：
            ${{ github.GITHUB_SHA }}\n
